// Generated by https://quicktype.io

export interface Trades {
  symbol:             string;
  companyName:        string;
  marketCap:          number;
  sector:             Sector;
  industry:           string;
  beta:               number;
  price:              number;
  lastAnnualDividend: number;
  volume:             number;
  exchange:           Exchange;
  exchangeShortName:  ExchangeShortName;
  country:            Country;
  isEtf:              boolean;
  isActivelyTrading:  boolean;
}

export enum Country {
  CA = "CA",
  IL = "IL",
  Ie = "IE",
  Ky = "KY",
  Nl = "NL",
  Sg = "SG",
  Us = "US",
  Uy = "UY",
}

export enum Exchange {
  NASDAQGlobalMarket = "NASDAQ Global Market",
  NASDAQGlobalSelect = "NASDAQ Global Select",
  NasdaqCapitalMarket = "Nasdaq Capital Market",
  NasdaqGlobalSelect = "Nasdaq Global Select",
}

export enum ExchangeShortName {
  Nasdaq = "NASDAQ",
}

export enum Sector {
  Technology = "Technology",
}
